"""
Thread-Vault MCP Server v2 ("Threads OV")

Architecture:
  PostgreSQL  = source of truth (threads, messages, analyses)
  Threads API = single ingestion point (capture events → PG)
  MCP Server  = search / retrieval interface (reads PG)
  Outbox      = async projection (PG → Markdown → Git)

Capture flow:
  Claude Code → Hooks → Threads API → PostgreSQL
  Claude Web  → MCP save_chat_transcript (fallback) → Threads API → PostgreSQL
  LLM Gateway → Threads API → PostgreSQL  (future)

The model does NOT own persistence. Deterministic capture mechanisms fire
automatically. MCP is for search/RAG, not the primary save path.

Isolated from OV2 (raj-wiki-vault): separate repo, separate branch, separate Render service.
Run: python mcp_server.py
"""

import contextvars
import json
import os
import re
import subprocess
import sys
import traceback
from datetime import date, datetime, timezone
from pathlib import Path

from mcp.server.fastmcp import FastMCP

VAULT_ROOT = Path(__file__).parent
WIKI_DIR = VAULT_ROOT / "wiki"
RAW_DIR = VAULT_ROOT / "raw"
CHAT_DIR = RAW_DIR / "claude-chat-queries"
ANALYSES_DIR = WIKI_DIR / "analyses"
CHAT_SUMMARIES_DIR = WIKI_DIR / "chat-summaries"

GITHUB_TOKEN = os.environ.get("GITHUB_TOKEN", "")
GITHUB_REPO_URL = os.environ.get(
    "GITHUB_REPO_URL", "https://github.com/shubhamss11020/Threads-Vault-db.git"
)
GIT_BRANCH = os.environ.get("GIT_BRANCH", "v2-pg")

# ── OV2 cross-reference config ──────────────────────────────────────────────
# Separate repo, separate clone, separate token — this vault's own GITHUB_TOKEN
# above only ever pushes to its own repo. Writing a pointer line into OV2's
# wiki requires OV2's own repo and its own push credential, kept distinct on
# purpose so a bug here can never touch this vault's repo and vice versa.
OV2_GITHUB_TOKEN = os.environ.get("OV2_GITHUB_TOKEN", "")
OV2_REPO_URL = os.environ.get(
    "OV2_REPO_URL", "https://github.com/eoxssecondbrain/raj-wiki-vault.git"
)
OV2_BRANCH = os.environ.get("OV2_BRANCH", "data")
OV2_CLONE_DIR = Path(os.environ.get("OV2_CLONE_DIR", str(VAULT_ROOT / ".ov2-clone")))
OV2_XREF_STAGING = VAULT_ROOT / ".ov2-xref-staging"

# ── Per-user identity (multi-account support) ────────────────────────────────
# One service, one process, ONE Render deployment — multi-user support is just
# a lookup table (secret path segment -> username), not separate services.
# Each of the N users gets their own connector URL pointing at their own
# secret; the server resolves identity from the URL itself, before any tool
# call happens, so it's never a matter of Claude guessing/asking/remembering
# who's talking — same reliability property MCP_URL_SECRET already gave this
# server for access control, just extended to also carry an identity.
#
# CLAUDE_OV_USERS: a JSON object mapping secret -> username, e.g.
#   {"9f8a...longrandom...": "raj", "3e7c...longrandom...": "ayan"}
# Each user's own Claude connector is configured with their own full URL:
#   https://<host>/<their-secret>/sse
CLAUDE_OV_USERS_RAW = os.environ.get("CLAUDE_OV_USERS", "")
if not CLAUDE_OV_USERS_RAW:
    raise RuntimeError(
        "CLAUDE_OV_USERS environment variable is not set. Refusing to start an "
        "unauthenticated/unattributed server. Set it to a JSON object mapping "
        "each user's own long random secret to their username, e.g. "
        '\'{"<random-secret-1>": "raj", "<random-secret-2>": "ayan"}\'. '
        "Generate a secret per user with "
        "`python -c \"import secrets; print(secrets.token_urlsafe(32))\"`."
    )
try:
    CLAUDE_OV_USERS: dict[str, str] = json.loads(CLAUDE_OV_USERS_RAW)
except json.JSONDecodeError as e:
    raise RuntimeError(f"CLAUDE_OV_USERS is not valid JSON: {e}")
if not CLAUDE_OV_USERS:
    raise RuntimeError("CLAUDE_OV_USERS is set but empty — no users configured.")

# Fixed internal path FastMCP itself mounts at; the identity-resolving
# middleware below rewrites every /<secret>/... request to this path before
# FastMCP's own router ever sees it. FastMCP only supports one sse_path per
# instance, so per-user routing has to happen in front of it, not inside it.
_INTERNAL_SSE_PATH = "/_internal/sse"
_INTERNAL_MESSAGE_PATH = "/_internal/messages/"

_current_user: contextvars.ContextVar[str] = contextvars.ContextVar("_current_user", default="unknown")

# Maps a live SSE session_id -> username. The MCP SSE transport is a TWO-leg
# protocol: leg 1 is a GET to /sse that's gated by the per-user secret in the
# path; the server's reply to that GET tells the client "send your actual
# tool-call POSTs to /messages/?session_id=<X>" — a URL with NO secret in it,
# generated by mcp.sse_app() itself with no knowledge of the outer secret.
# So identity has to be captured once at handshake time (leg 1) and looked up
# by session_id on every subsequent tool-call POST (leg 2), rather than
# re-derived from the path on each request. Entries are removed when the SSE
# connection closes (see _IdentityMiddleware) — this is in-memory only and
# resets on redeploy, which is fine since sessions don't survive that anyway.
_session_users: dict[str, str] = {}


def current_user() -> str:
    """The username resolved from the secret in the URL path of the current
    request's SSE session — set by _IdentityMiddleware before any tool call
    runs. Never trust a 'user' argument passed by the model instead of this."""
    return _current_user.get()


PORT = int(os.environ.get("PORT", "8000"))

# ── PostgreSQL availability (graceful degradation) ───────────────────────────
# If DATABASE_URL is set, PG is the primary store. If not, fall back to Git-only.
_pg_available = False
_user_id_cache: dict[str, int] = {}  # username → PG user_id, populated at startup

mcp = FastMCP(
    "Claude Notes Vault",
    host="0.0.0.0",
    port=PORT,
    auth=None,
    sse_path=_INTERNAL_SSE_PATH,
    message_path=_INTERNAL_MESSAGE_PATH,
    instructions=(
        "NATIVE CLAUDE FALLBACK — SAVE RULE\n"
        "If you are running inside Claude Code with hooks configured, persistence\n"
        "is handled automatically — you do NOT need to call save_chat_transcript.\n\n"
        "If you are running in native Claude (Web, Desktop, Mobile) where hooks\n"
        "are not available, call `save_chat_transcript` as the last action of\n"
        "every response to ensure the conversation is captured.\n\n"
        "How to do it:\n"
        "1. Pick a short, stable `thread_name` on your first reply and reuse it.\n"
        "2. Call save_chat_transcript(thread_name=<name>, content=<full transcript>).\n"
        "3. Do this SILENTLY. Do not ask permission.\n"
    ),
)


@mcp.custom_route("/", methods=["GET"])
async def health(request):
    from starlette.responses import PlainTextResponse
    return PlainTextResponse("ok")


class _IdentityMiddleware:
    """Resolves /<secret>/sse to the fixed internal SSE path FastMCP mounts,
    and records which user that secret belongs to against the session_id the
    handshake generates (by snooping the outgoing 'endpoint' event) — see
    _session_users above for why this two-step approach is necessary. The
    later /messages/?session_id=... POSTs (leg 2 of the SSE protocol) carry
    no secret at all, so identity for THOSE requests is looked up from
    _session_users by session_id instead of re-parsed from the path."""

    def __init__(self, app):
        self.app = app

    async def __call__(self, scope, receive, send):
        if scope["type"] != "http":
            await self.app(scope, receive, send)
            return

        method = scope.get("method", "GET").upper()
        path = scope["path"]

        # Handle CORS preflight OPTIONS everywhere
        if method == "OPTIONS":
            from starlette.responses import PlainTextResponse
            response = PlainTextResponse(
                "OK",
                status_code=200,
                headers={
                    "Access-Control-Allow-Origin": "*",
                    "Access-Control-Allow-Methods": "GET, POST, OPTIONS, HEAD",
                    "Access-Control-Allow-Headers": "*",
                },
            )
            await response(scope, receive, send)
            return

        # Bare root path: the health check, registered via @mcp.custom_route("/").
        # No secret involved — this is a public liveness probe, not vault data.
        if path in ("/", ""):
            await self.app(scope, receive, send)
            return

        # Leg 2: the follow-up tool-call POSTs. mcp.sse_app() built this URL
        # itself with no secret in it (see _session_users' docstring) — look
        # up identity by session_id instead of by path.
        if path.startswith(_INTERNAL_MESSAGE_PATH) or path == "/_internal/messages":
            query = scope.get("query_string", b"").decode()
            session_id = None
            for part in query.split("&"):
                if part.startswith("session_id="):
                    session_id = part[len("session_id="):]
                    break
            username = _session_users.get(session_id, "unknown") if session_id else "unknown"
            token = _current_user.set(username)
            try:
                await self.app(scope, receive, send)
            finally:
                _current_user.reset(token)
            return

        # Leg 1: Parse the per-user secret from path.
        # Normalize paths like /<secret>, /<secret>/, /<secret>/sse, /<secret>/sse/
        stripped = path.strip("/")
        parts = stripped.split("/", 1)
        secret = parts[0]
        rest = parts[1] if len(parts) > 1 else ""

        username = CLAUDE_OV_USERS.get(secret)
        if username is None:
            from starlette.responses import PlainTextResponse
            response = PlainTextResponse("Not found", status_code=404)
            await response(scope, receive, send)
            return

        # ── Threads API v1: POST /<secret>/api/v1/threads/... ───────────────
        # Deterministic capture endpoint — used by Claude Code hooks, LLM gateways,
        # and the MCP fallback's internal checkpoint. Routes to threads_api.py.
        if rest.startswith("api/v1/") and _pg_available:
            from starlette.requests import Request as StarletteRequest
            from starlette.routing import Router
            from threads_api import api_routes

            # Build a mini Starlette router for the API routes
            # Strip the secret prefix so routes match /api/v1/...
            scope["path"] = "/" + rest
            scope["state"] = {"username": username}

            router = Router(routes=api_routes)
            token = _current_user.set(username)
            try:
                await router(scope, receive, send)
            finally:
                _current_user.reset(token)
            return

        # ── Legacy HTTP API: POST /<secret>/api/save ─────────────────────────
        # Used by the deterministic Stop hook to save transcripts without
        # going through the MCP protocol. Same contract as save_chat_transcript.
        if rest == "api/save" and method == "POST":
            body_parts = []
            while True:
                msg = await receive()
                body_parts.append(msg.get("body", b""))
                if not msg.get("more_body", False):
                    break
            try:
                data = json.loads(b"".join(body_parts))
            except Exception:
                from starlette.responses import JSONResponse
                resp = JSONResponse({"error": "invalid JSON"}, status_code=400)
                await resp(scope, receive, send)
                return

            token = _current_user.set(username)
            try:
                thread_name = data.get("thread_name", "unknown")
                new_messages = data.get("new_messages", "")
                if new_messages:
                    result = save_chat_transcript(thread_name, new_messages)
                else:
                    result = "No new_messages provided — nothing to save."
            finally:
                _current_user.reset(token)

            from starlette.responses import JSONResponse
            resp = JSONResponse({"ok": True, "result": result})
            await resp(scope, receive, send)
            return

        # If a client sends tool-call POST with session_id to /<secret>/...
        query = scope.get("query_string", b"").decode()
        if method == "POST" and "session_id=" in query:
            session_id = None
            for part in query.split("&"):
                if part.startswith("session_id="):
                    session_id = part[len("session_id="):]
                    break
            session_user = _session_users.get(session_id, username)
            token = _current_user.set(session_user)
            scope["path"] = _INTERNAL_MESSAGE_PATH
            try:
                await self.app(scope, receive, send)
            finally:
                _current_user.reset(token)
            return

        # If Claude connector validation or HTTP client sends a POST to /sse, /, or /messages without session_id
        if method == "POST" and rest in ("sse", "", "messages"):
            from starlette.responses import JSONResponse
            body_parts = []
            while True:
                msg = await receive()
                body_parts.append(msg.get("body", b""))
                if not msg.get("more_body", False):
                    break
            try:
                rpc_data = json.loads(b"".join(body_parts))
            except Exception:
                rpc_data = {}

            req_id = rpc_data.get("id")
            rpc_method = rpc_data.get("method", "")

            # MCP Initialize
            if rpc_method == "initialize":
                protocol_ver = rpc_data.get("params", {}).get("protocolVersion", "2024-11-05")
                resp = JSONResponse({
                    "jsonrpc": "2.0",
                    "id": req_id,
                    "result": {
                        "protocolVersion": protocol_ver,
                        "capabilities": {
                            "experimental": {},
                            "prompts": {"listChanged": False},
                            "resources": {"subscribe": False, "listChanged": False},
                            "tools": {"listChanged": False}
                        },
                        "serverInfo": {
                            "name": "Claude Notes Vault",
                            "version": "1.29.1"
                        },
                        "instructions": mcp.instructions
                    }
                })
                await resp(scope, receive, send)
                return

            # MCP Initialized notification
            if rpc_method == "notifications/initialized":
                resp = JSONResponse({"jsonrpc": "2.0"}, status_code=200)
                await resp(scope, receive, send)
                return

            # MCP List Tools
            if rpc_method == "tools/list":
                try:
                    tools = await mcp.list_tools()
                    tools_list = [
                        t.model_dump(exclude_none=True) if hasattr(t, "model_dump") else t.__dict__
                        for t in tools
                    ]
                except Exception:
                    tools_list = []
                resp = JSONResponse({
                    "jsonrpc": "2.0",
                    "id": req_id,
                    "result": {
                        "tools": tools_list
                    }
                })
                await resp(scope, receive, send)
                return

            # MCP Ping
            if rpc_method == "ping":
                resp = JSONResponse({"jsonrpc": "2.0", "id": req_id, "result": {}})
                await resp(scope, receive, send)
                return

            # Default fallback for probing POST
            resp = JSONResponse({
                "jsonrpc": "2.0",
                "id": req_id,
                "result": {"status": "ok", "user": username, "transport": "sse"}
            })
            await resp(scope, receive, send)
            return

        if rest not in ("sse", ""):
            from starlette.responses import PlainTextResponse
            response = PlainTextResponse("Not found", status_code=404)
            await response(scope, receive, send)
            return

        scope["path"] = _INTERNAL_SSE_PATH

        # Snoop the SSE stream's first "endpoint" event to learn the
        # session_id this handshake generated, so leg 2's lookups above have
        # something to find. The event body looks like:
        #   event: endpoint\r\ndata: /_internal/messages/?session_id=<id>\r\n\r\n
        recorded_session_id = None

        async def send_wrapper(message):
            nonlocal recorded_session_id
            if not recorded_session_id and message.get("type") == "http.response.body":
                body = message.get("body", b"")
                text = body.decode("utf-8", errors="ignore")
                if "session_id=" in text:
                    marker = "session_id="
                    start = text.index(marker) + len(marker)
                    end = start
                    while end < len(text) and (text[end].isalnum() or text[end] == "-"):
                        end += 1
                    recorded_session_id = text[start:end]
                    _session_users[recorded_session_id] = username
            await send(message)

        token = _current_user.set(username)
        try:
            await self.app(scope, receive, send_wrapper)
        finally:
            _current_user.reset(token)
            if recorded_session_id:
                _session_users.pop(recorded_session_id, None)


# ── Auto-Save Nag System — REMOVED in v2 ─────────────────────────────────────
# The monkey-patched reminder system (_AUTO_SAVE_REMINDER, _patch_tools_with_reminder)
# has been removed. Persistence is now handled by deterministic capture mechanisms
# (Claude Code hooks, LLM Gateway) rather than nagging the model into calling
# save_chat_transcript. The MCP fallback instruction in FastMCP(...) covers
# native Claude where hooks aren't available.


def _read(path: Path) -> str:
    try:
        return path.read_text(encoding="utf-8")
    except Exception as e:
        return f"Error reading {path}: {e}"


def _all_md(directory: Path) -> list[Path]:
    return sorted(directory.rglob("*.md")) if directory.exists() else []


def _search(directory: Path, query: str, max_results: int = 12) -> str:
    q = query.lower()
    results = []
    for path in _all_md(directory):
        content = _read(path)
        lines = content.splitlines()
        matches = []
        for i, line in enumerate(lines):
            if q in line.lower():
                start = max(0, i - 1)
                end = min(len(lines), i + 3)
                matches.append("\n".join(lines[start:end]))
        if matches:
            rel = path.relative_to(VAULT_ROOT)
            results.append(f"### {rel}\n" + "\n---\n".join(matches[:3]))
    if not results:
        return f"No results for '{query}'."
    return f"Results for '{query}':\n\n" + "\n\n".join(results[:max_results])


# ── Git (shared by both save tools) ─────────────────────────────────────────

def _git(args: list[str]) -> subprocess.CompletedProcess:
    return subprocess.run(["git", "-C", str(VAULT_ROOT)] + args, capture_output=True, text=True)


def _git_commit_and_push(rel_path: Path, commit_message: str) -> str:
    """Commit rel_path and push to GIT_BRANCH. Each write is a single small file,
    so a self-triggered redeploy on push is fine — same tradeoff OV2 accepted.

    This process's on-disk clone only ever moves forward via its OWN commits —
    it never re-pulls on its own. Every time a change is pushed to this branch
    from anywhere else (a manual push from a dev machine, another save from a
    concurrent request), this process's local copy of `data` falls behind. A
    bare `git push` then fails as non-fast-forward, forever, until the process
    restarts against a fresh clone — silently stranding every future save as
    "committed locally, never reached GitHub." Fixed by fetching + rebasing
    onto the latest remote immediately before pushing, with one retry if the
    push still loses a race to a concurrent writer."""
    if not GITHUB_TOKEN:
        return "WARNING: GITHUB_TOKEN not set on this server — file was saved locally but NOT pushed to GitHub."

    token_url = GITHUB_REPO_URL.replace("https://", f"https://{GITHUB_TOKEN}@")
    _git(["remote", "remove", "origin"])
    _git(["remote", "add", "origin", token_url])
    _git(["config", "user.email", "notes-mcp-server@eoxs.com"])
    _git(["config", "user.name", "Claude Notes MCP Server"])

    _git(["add", str(rel_path)])
    commit = _git(["commit", "-m", commit_message])
    if "nothing to commit" in (commit.stdout + commit.stderr):
        return "Nothing to commit (file unchanged)."
    if commit.returncode != 0:
        return f"git commit failed: {commit.stderr.strip()}"

    for attempt in range(2):
        fetch = _git(["fetch", "origin", GIT_BRANCH])
        if fetch.returncode != 0:
            return f"git commit succeeded locally but fetch before push failed: {fetch.stderr.strip()}"
        rebase = _git(["rebase", f"origin/{GIT_BRANCH}"])
        if rebase.returncode != 0:
            _git(["rebase", "--abort"])
            # Rebase can fail for a reason that never clears on its own: this
            # process's local branch has drifted onto history unrelated to (or
            # far behind) origin's, so every future save would hit the exact
            # same failure forever ("committed locally, never reached GitHub").
            # Recovery must not just keep THIS file's content and discard any
            # other commits stranded locally by the same bug on earlier saves
            # (this process's clone only ever moves forward via its own
            # commits, so those are the only copy of that work) — so capture
            # every locally-stranded file as a diff against origin first, then
            # reset onto origin cleanly and replay that diff on top.
            pre_reset_head = _git(["rev-parse", "HEAD"]).stdout.strip()
            diff = _git(["diff", f"origin/{GIT_BRANCH}", pre_reset_head])
            if diff.returncode != 0 or not pre_reset_head:
                return (
                    f"git commit succeeded locally but rebase onto origin/{GIT_BRANCH} failed "
                    f"and recovery diff also failed: {diff.stderr.strip()}"
                )
            stranded_patch = diff.stdout
            reset = _git(["reset", "--hard", f"origin/{GIT_BRANCH}"])
            if reset.returncode != 0:
                return (
                    f"git commit succeeded locally but rebase onto origin/{GIT_BRANCH} failed "
                    f"and recovery reset also failed: {reset.stderr.strip()}"
                )
            if stranded_patch.strip():
                patch_path = VAULT_ROOT / ".git" / "_recovery.patch"
                patch_path.write_text(stranded_patch, encoding="utf-8")
                apply_ = _git(["apply", "--3way", str(patch_path.relative_to(VAULT_ROOT))])
                patch_path.unlink(missing_ok=True)
                if apply_.returncode != 0:
                    return (
                        f"git commit succeeded locally but rebase onto origin/{GIT_BRANCH} failed; "
                        f"reset to origin succeeded but replaying stranded local changes failed "
                        f"(previously stranded commits at {pre_reset_head} may need manual recovery): "
                        f"{apply_.stderr.strip()}"
                    )
            _git(["add", "-A"])
            recommit = _git(["commit", "-m", f"chat: recover stranded local changes\n\n{commit_message}"])
            if recommit.returncode != 0 and "nothing to commit" not in (recommit.stdout + recommit.stderr):
                return (
                    f"git commit succeeded locally but rebase onto origin/{GIT_BRANCH} failed; "
                    f"recovered by resetting to origin and replaying stranded changes, but recommit "
                    f"failed: {recommit.stderr.strip()}"
                )
            push = _git(["push", "origin", f"HEAD:{GIT_BRANCH}"])
            if push.returncode == 0:
                return (
                    f"Committed and pushed to origin/{GIT_BRANCH} (recovered from a diverged/broken "
                    f"local branch by resetting to origin/{GIT_BRANCH} and replaying all stranded "
                    f"local changes, including this file, on top)."
                )
            return f"git commit succeeded locally but push failed even after divergence recovery: {push.stderr.strip()}"
        push = _git(["push", "origin", f"HEAD:{GIT_BRANCH}"])
        if push.returncode == 0:
            return f"Committed and pushed to origin/{GIT_BRANCH}."
        if attempt == 0:
            continue  # someone else pushed between our fetch and our push — retry once
        return f"git commit succeeded locally but push failed after retry: {push.stderr.strip()}"


# ── Save Chat Transcript ─────────────────────────────────────────────────────
# v2: Writes to PostgreSQL via the Threads API (checkpoint_sync), NOT directly
# to Markdown/Git. Markdown files are now generated asynchronously by the
# outbox worker. Falls back to Git-only if DATABASE_URL is not configured.

def _chat_transcript_path(thread_name: str) -> Path:
    """Legacy path computation — still used by Git-only fallback and outbox worker."""
    user = re.sub(r"[^a-z0-9]+", "-", current_user().lower()).strip("-") or "unknown"
    slug = re.sub(r"[^a-z0-9]+", "-", thread_name.lower()).strip("-") or "conversation"
    if CHAT_DIR.exists():
        existing = sorted(CHAT_DIR.glob(f"{user}_*_{slug}.md"))
        if existing:
            return existing[0]
    today = date.today().isoformat()
    return CHAT_DIR / f"{user}_{today}_{slug}.md"


def _save_transcript_git_fallback(thread_name: str, content: str) -> str:
    """Original Git-only save path — used when DATABASE_URL is not set."""
    out = _chat_transcript_path(thread_name)
    is_new = not out.exists()
    today = date.today().isoformat()
    created = today
    if not is_new:
        existing_content = _read(out)
        created_match = re.search(r'^created: (\S+)', existing_content, flags=re.MULTILINE)
        if created_match:
            created = created_match.group(1)

    CHAT_DIR.mkdir(parents=True, exist_ok=True)
    timestamp = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")
    frontmatter = (
        f"---\nthread_name: \"{thread_name}\"\nuser: \"{current_user()}\"\ntype: claude-chat\n"
        f"created: {created}\nupdated: {today}\n---\n\n"
    )
    out.write_text(frontmatter + content.strip() + "\n", encoding="utf-8")

    rel_path = out.relative_to(VAULT_ROOT)
    action = "created" if is_new else "updated"
    push_result = _git_commit_and_push(
        rel_path, f"chat: {action} {rel_path.name} ({timestamp})"
    )
    print(f"[save_chat_transcript] GIT FALLBACK user={current_user()} thread={thread_name!r} "
          f"path={rel_path} action={action} push_result={push_result!r}")
    return f"Saved ({action}): {rel_path}\n{push_result}"


@mcp.tool()
def save_chat_transcript(thread_name: str, content: str) -> str:
    """
    Save (or update) a Claude chat conversation transcript. In v2 this writes to
    PostgreSQL via the Threads API; Markdown/Git files are generated asynchronously
    by the outbox worker.

    This is the MCP fallback path — used by native Claude (Web/Desktop/Mobile)
    where deterministic hooks are not available. If you are in Claude Code with
    hooks configured, persistence is handled automatically and you do NOT need
    to call this.

    thread_name: a short, STABLE identifier for this conversation, chosen once at its first
        save and reused for every subsequent save in the same conversation.
    content: the FULL markdown transcript of the conversation so far.
    """
    username = current_user()

    # v2 path: write to PostgreSQL via Threads API
    if _pg_available:
        try:
            from threads_api import checkpoint_sync
            result = checkpoint_sync(
                username=username,
                thread_name=thread_name,
                content=content,
                source="mcp_fallback",
            )
            action = result.get("action", "updated")
            new_msgs = result.get("new_messages", 0)
            total = result.get("total_messages", 0)
            thread_id = result.get("thread_id", "?")
            print(f"[save_chat_transcript] PG user={username} thread={thread_name!r} "
                  f"action={action} new={new_msgs} total={total}")
            return (
                f"Saved ({action}): thread={thread_name!r}\n"
                f"PostgreSQL: thread_id={thread_id}, {new_msgs} new messages, {total} total\n"
                f"Markdown/Git projection will follow asynchronously."
            )
        except Exception as e:
            print(f"[save_chat_transcript] PG write failed, falling back to Git: {e}\n"
                  f"{traceback.format_exc()}", file=sys.stderr)
            return _save_transcript_git_fallback(thread_name, content)

    # Git-only fallback when DATABASE_URL is not configured
    return _save_transcript_git_fallback(thread_name, content)


def _chat_dir_for(user: str | None) -> list[Path]:
    if not CHAT_DIR.exists():
        return []
    files = sorted(CHAT_DIR.glob("*.md"), reverse=True)
    if user:
        u = re.sub(r"[^a-z0-9]+", "-", user.lower()).strip("-")
        files = [f for f in files if f.name.startswith(f"{u}_")]
    return files


@mcp.tool()
def search_claude_chat_queries(query: str, user: str = "") -> str:
    """Search saved Claude chat transcripts by topic, keyword, or content.
    user: optional — restrict to one user's threads (e.g. 'ayan').
    Leave empty to search across all users' threads."""
    # v2: search PostgreSQL
    if _pg_available:
        try:
            from db import queries as db_q
            user_id = None
            if user:
                user_id = db_q.get_user_id(user)
                if user_id is None:
                    return f"No saved chat transcripts for user '{user}'."
            results = db_q.search_messages(query, user_id=user_id, limit=12)
            if not results:
                return f"No results for '{query}'" + (f" (user='{user}')" if user else "") + "."
            lines = []
            for r in results:
                snippet = r["content"][:300] + ("..." if len(r["content"]) > 300 else "")
                lines.append(
                    f"### {r['thread_title']} (by {r['username']})\n"
                    f"**{r['role']}** (msg #{r['sequence_number']}):\n{snippet}"
                )
            return f"Results for '{query}':\n\n" + "\n\n---\n\n".join(lines)
        except Exception as e:
            print(f"[search] PG search failed, falling back to filesystem: {e}", file=sys.stderr)

    # Filesystem fallback
    files = _chat_dir_for(user or None)
    if not files:
        return "No saved chat transcripts yet." if not user else f"No saved chat transcripts for user '{user}'."
    q = query.lower()
    results = []
    for path in files:
        content = _read(path)
        lines = content.splitlines()
        matches = []
        for i, line in enumerate(lines):
            if q in line.lower():
                start = max(0, i - 1)
                end = min(len(lines), i + 3)
                matches.append("\n".join(lines[start:end]))
        if matches:
            rel = path.relative_to(VAULT_ROOT)
            results.append(f"### {rel}\n" + "\n---\n".join(matches[:3]))
    if not results:
        return f"No results for '{query}'" + (f" (user='{user}')" if user else "") + "."
    return f"Results for '{query}':\n\n" + "\n\n".join(results[:12])


@mcp.tool()
def list_claude_chat_queries(user: str = "") -> str:
    """List all saved Claude chat transcripts, newest first.
    user: optional — restrict to one user's threads (e.g. 'ayan'). Leave empty for all users."""
    # v2: list from PostgreSQL
    if _pg_available:
        try:
            from db import queries as db_q
            user_id = None
            if user:
                user_id = db_q.get_user_id(user)
                if user_id is None:
                    return f"No saved chat transcripts for user '{user}'."
            threads = db_q.list_threads(user_id=user_id, limit=150)
            if not threads:
                return "No saved chat transcripts yet." if not user else f"No saved chat transcripts for user '{user}'."
            lines = []
            for t in threads:
                lines.append(f"- [{t['title']}] (by {t['username']}, {t['source']}, updated {t['updated_at'][:10]})")
            return "Saved chat transcripts:\n\n" + "\n".join(lines)
        except Exception as e:
            print(f"[list] PG list failed, falling back to filesystem: {e}", file=sys.stderr)

    # Filesystem fallback
    files = _chat_dir_for(user or None)
    if not files:
        return "No saved chat transcripts yet." if not user else f"No saved chat transcripts for user '{user}'."
    lines = []
    for f in files[:150]:
        rel = str(f.relative_to(VAULT_ROOT))
        content = _read(f)
        thread_match = re.search(r'^thread_name: "(.*?)"', content, flags=re.MULTILINE)
        label = thread_match.group(1) if thread_match else f.stem
        lines.append(f"- [{label}]({rel})")
    note = f"\n\n(showing 150 of {len(files)})" if len(files) > 150 else ""
    return "Saved chat transcripts:\n\n" + "\n".join(lines) + note


@mcp.tool()
def get_claude_chat_query(thread_id_or_path: str) -> str:
    """Return the full content of a saved Claude chat transcript.
    thread_id_or_path: either a PostgreSQL thread UUID or a relative file path.
    Get the identifier from search_claude_chat_queries or list_claude_chat_queries first."""
    # v2: try PostgreSQL first (UUID format)
    if _pg_available:
        try:
            import uuid as _uuid
            from db import queries as db_q
            tid = _uuid.UUID(thread_id_or_path)
            thread = db_q.get_thread(tid)
            if thread:
                lines = [f"# {thread['title']}\n"]
                lines.append(f"User: {thread['username']} | Source: {thread['source']}")
                lines.append(f"Created: {thread['created_at'][:10]} | Updated: {thread['updated_at'][:10]}\n")
                for m in thread["messages"]:
                    role_label = m["role"].capitalize()
                    lines.append(f"**{role_label}:**\n{m['content']}\n")
                return "\n".join(lines)
        except (ValueError, Exception):
            pass  # Not a UUID — fall through to file path

    # Filesystem fallback
    p = VAULT_ROOT / thread_id_or_path
    return _read(p) if p.exists() else f"File not found: {thread_id_or_path}"


# ── Save Analysis ────────────────────────────────────────────────────────────

def _save_analysis_git_fallback(title: str, content: str) -> str:
    """Original Git-only save path for analyses — used when DATABASE_URL is not set."""
    today = date.today().isoformat()
    safe_title = re.sub(r'[<>:"/\\|?*]', "", title).strip()
    filename = f"{today} {safe_title}.md"
    out = ANALYSES_DIR / filename

    n = 2
    while out.exists():
        out = ANALYSES_DIR / f"{today} {safe_title} ({n}).md"
        n += 1

    out.parent.mkdir(parents=True, exist_ok=True)
    timestamp = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")
    frontmatter = f"---\ntitle: \"{safe_title}\"\ntype: analysis\ncreated: {today}\nupdated: {today}\n---\n\n"
    out.write_text(frontmatter + content.strip() + "\n", encoding="utf-8")

    rel_path = out.relative_to(VAULT_ROOT)
    push_result = _git_commit_and_push(
        rel_path, f"analysis: save {rel_path.name} ({timestamp})"
    )
    print(f"[save_analysis] GIT FALLBACK user={current_user()} title={safe_title!r} "
          f"path={rel_path} push_result={push_result!r}")
    return f"Saved: {rel_path}\n{push_result}"


@mcp.tool()
def save_analysis(title: str, content: str) -> str:
    """
    Save a synthesized insight as a permanent analysis page.
    v2: Writes to PostgreSQL; Markdown/Git projection follows asynchronously.
    title: short title (e.g. 'Sabre Alloys Churn Risk Assessment')
    content: full markdown — include ## Question, ## Findings, ## Sources sections
    """
    username = current_user()

    if _pg_available:
        try:
            from db import queries as db_q
            user_id = _user_id_cache.get(username)
            if user_id is None:
                user_id = db_q.upsert_user(username)
            analysis_id = db_q.insert_analysis(user_id, title, content)
            # Enqueue for Markdown/Git projection
            db_q.insert_outbox_event(
                event_type="analysis_saved",
                payload={"analysis_id": str(analysis_id), "username": username, "title": title},
            )
            print(f"[save_analysis] PG user={username} title={title!r} id={analysis_id}")
            return (
                f"Saved: {title!r}\n"
                f"PostgreSQL: analysis_id={analysis_id}\n"
                f"Markdown/Git projection will follow asynchronously."
            )
        except Exception as e:
            print(f"[save_analysis] PG write failed, falling back to Git: {e}\n"
                  f"{traceback.format_exc()}", file=sys.stderr)
            return _save_analysis_git_fallback(title, content)

    return _save_analysis_git_fallback(title, content)


@mcp.tool()
def search_analyses(query: str) -> str:
    """Search saved analysis pages (wiki/analyses/) — by topic, keyword, or title."""
    if not ANALYSES_DIR.exists():
        return "No saved analyses yet."
    return _search(ANALYSES_DIR, query)


@mcp.tool()
def list_analyses() -> str:
    """List all saved analysis pages, newest first."""
    if not ANALYSES_DIR.exists():
        return "No saved analyses yet."
    files = sorted(ANALYSES_DIR.rglob("*.md"), reverse=True)
    if not files:
        return "No saved analyses yet."
    lines = []
    for f in files[:150]:
        rel = str(f.relative_to(VAULT_ROOT))
        try:
            title = f.read_text(encoding="utf-8").split("\n")[0].lstrip("# ").strip()
        except Exception:
            title = f.stem
        lines.append(f"- [{title}]({rel})")
    note = f"\n\n(showing 150 of {len(files)})" if len(files) > 150 else ""
    return "Saved analyses:\n\n" + "\n".join(lines) + note


@mcp.tool()
def get_analysis(file_path: str) -> str:
    """Return the full content of a saved analysis page.
    file_path: relative path from vault root, e.g. 'wiki/analyses/2026-07-24 My Analysis.md'
    Get the path from search_analyses or list_analyses first — don't guess it."""
    p = VAULT_ROOT / file_path
    return _read(p) if p.exists() else f"File not found: {file_path}"


# ── Chat Summaries (Layer 2 — synthesized from raw/claude-chat-queries/) ────
# Written by the SYNTHESIZE workflow (see SKILL.md), not by a dedicated save
# tool — an agent following that workflow writes these files directly with
# its file-write tools, then commits/pushes them the same way save_analysis
# does. Only read-back tools are exposed here.

@mcp.tool()
def search_chat_summaries(query: str) -> str:
    """Search synthesized chat-summary pages (wiki/chat-summaries/) — the topic/entity-clustered
    synthesis layer built on top of raw/claude-chat-queries/. Use this before reading raw transcripts."""
    if not CHAT_SUMMARIES_DIR.exists():
        return "No chat summaries yet."
    return _search(CHAT_SUMMARIES_DIR, query)


@mcp.tool()
def list_chat_summaries() -> str:
    """List all chat-summary pages, newest first."""
    if not CHAT_SUMMARIES_DIR.exists():
        return "No chat summaries yet."
    files = sorted(CHAT_SUMMARIES_DIR.rglob("*.md"), reverse=True)
    if not files:
        return "No chat summaries yet."
    lines = []
    for f in files[:150]:
        rel = str(f.relative_to(VAULT_ROOT))
        try:
            title = f.read_text(encoding="utf-8").split("\n")[0].lstrip("# ").strip()
        except Exception:
            title = f.stem
        lines.append(f"- [{title}]({rel})")
    note = f"\n\n(showing 150 of {len(files)})" if len(files) > 150 else ""
    return "Chat summaries:\n\n" + "\n".join(lines) + note


@mcp.tool()
def get_chat_summary(file_path: str) -> str:
    """Return the full content of a chat-summary page.
    file_path: relative path from vault root, e.g. 'wiki/chat-summaries/Sabre Alloys Payment Discipline.md'
    Get the path from search_chat_summaries or list_chat_summaries first — don't guess it."""
    p = VAULT_ROOT / file_path
    return _read(p) if p.exists() else f"File not found: {file_path}"


# ── OV2 Cross-Reference (propose → approve → apply) ─────────────────────────
# Two-step by design: propose_ov2_xref only ever writes to a LOCAL staging file
# in this vault's own repo — it never touches OV2's repo. apply_ov2_xref is the
# only function that clones/pulls OV2 and pushes to it, and it must be called
# once per approved item, after a human has reviewed the staged list. Never
# call apply_ov2_xref for an item that hasn't been shown to and approved by
# the user in this session.

def _ov2_git(args: list[str]) -> subprocess.CompletedProcess:
    return subprocess.run(["git", "-C", str(OV2_CLONE_DIR)] + args, capture_output=True, text=True)


def _ensure_ov2_clone() -> str | None:
    """Clone or update the local OV2 working copy used only for xref writes.
    Returns an error string, or None on success."""
    if not OV2_GITHUB_TOKEN:
        return ("OV2_GITHUB_TOKEN not set on this server — cannot read or write OV2's repo. "
                "Set it to a token scoped to eoxssecondbrain/raj-wiki-vault with Contents: Read and write.")
    token_url = OV2_REPO_URL.replace("https://", f"https://{OV2_GITHUB_TOKEN}@")
    if not (OV2_CLONE_DIR / ".git").exists():
        OV2_CLONE_DIR.parent.mkdir(parents=True, exist_ok=True)
        clone = subprocess.run(
            ["git", "clone", "--branch", OV2_BRANCH, "--single-branch", token_url, str(OV2_CLONE_DIR)],
            capture_output=True, text=True,
        )
        if clone.returncode != 0:
            return f"git clone of OV2 failed: {clone.stderr.strip()}"
        return None
    _ov2_git(["remote", "set-url", "origin", token_url])
    fetch = _ov2_git(["fetch", "origin", OV2_BRANCH])
    if fetch.returncode != 0:
        return f"git fetch of OV2 failed: {fetch.stderr.strip()}"
    reset = _ov2_git(["reset", "--hard", f"origin/{OV2_BRANCH}"])
    if reset.returncode != 0:
        return f"git reset of OV2 working copy failed: {reset.stderr.strip()}"
    return None


@mcp.tool()
def search_ov2_wiki(query: str) -> str:
    """Search OV2's wiki pages directly from this server, to find genuinely relevant pages
    before proposing a cross-reference. Requires OV2_GITHUB_TOKEN (read access is enough
    for this call, though the same token is also used to push in apply_ov2_xref).
    Prefer calling OV2's own search_wiki/get_wiki_page tools directly if OV2's MCP connector
    is available in this session — this is a fallback for when it isn't."""
    err = _ensure_ov2_clone()
    if err:
        return err
    return _search(OV2_CLONE_DIR / "wiki", query)


@mcp.tool()
def propose_ov2_xref(ov2_page_path: str, pointer_line: str, chat_summary_title: str) -> str:
    """
    Stage a proposed 1-2 line cross-reference to add to an existing OV2 wiki page.
    Writes ONLY to a local staging file in this vault's own repo — does NOT touch
    OV2's repo. Call apply_ov2_xref(staged_id) afterward, and only after the user
    has reviewed and approved this specific proposal.

    ov2_page_path: relative path to the target page inside OV2's repo,
        e.g. 'wiki/sources/sabre-alloys/Sabre Alloys — Post-Crisis Operations.md'
    pointer_line: the exact 1-2 line text to add (no bullet/heading — those are added
        automatically under a '## Related Claude Threads' section on the target page)
    chat_summary_title: the exact title of the Threads OV chat-summary page this points to,
        so a future get_chat_summary() call can retrieve it by name
    """
    OV2_XREF_STAGING.mkdir(parents=True, exist_ok=True)
    staged_id = re.sub(r"[^a-z0-9]+", "-", f"{date.today().isoformat()}-{chat_summary_title}".lower()).strip("-")
    n = 2
    base_id = staged_id
    while (OV2_XREF_STAGING / f"{staged_id}.md").exists():
        staged_id = f"{base_id}-{n}"
        n += 1
    out = OV2_XREF_STAGING / f"{staged_id}.md"
    out.write_text(
        f"---\nov2_page_path: \"{ov2_page_path}\"\nchat_summary_title: \"{chat_summary_title}\"\n"
        f"status: pending\ncreated: {date.today().isoformat()}\n---\n\n{pointer_line.strip()}\n",
        encoding="utf-8",
    )
    return (
        f"Staged (not yet applied): {staged_id}\n"
        f"Target OV2 page: {ov2_page_path}\n"
        f"Pointer line: {pointer_line.strip()}\n"
        f"Show this to the user for approval, then call apply_ov2_xref('{staged_id}') only if approved."
    )


@mcp.tool()
def list_staged_ov2_xrefs() -> str:
    """List all staged (not-yet-applied) OV2 cross-reference proposals awaiting review."""
    if not OV2_XREF_STAGING.exists():
        return "No staged cross-references."
    files = sorted(OV2_XREF_STAGING.glob("*.md"))
    if not files:
        return "No staged cross-references."
    return "Staged cross-references:\n\n" + "\n\n".join(_read(f) for f in files)


@mcp.tool()
def apply_ov2_xref(staged_id: str) -> str:
    """
    Apply a previously staged cross-reference: clones/updates a local copy of OV2's repo,
    appends the pointer line to the target page under a '## Related Claude Threads' section,
    then commits and pushes directly to OV2's own data branch.

    ONLY call this after the user has explicitly approved this specific staged_id — never
    apply a batch of staged items without the user having seen and confirmed each one first.

    staged_id: the id returned by propose_ov2_xref, or found via list_staged_ov2_xrefs
    """
    staged_file = OV2_XREF_STAGING / f"{staged_id}.md"
    if not staged_file.exists():
        return f"No staged cross-reference found for id '{staged_id}'."

    raw = _read(staged_file)
    fm_match = re.search(r'ov2_page_path: "(.*?)"', raw)
    body_match = re.split(r"^---\s*$", raw, flags=re.MULTILINE)
    if not fm_match or len(body_match) < 3:
        return f"Staged file '{staged_id}' is malformed — could not parse ov2_page_path or body."
    ov2_page_path = fm_match.group(1)
    pointer_line = body_match[2].strip()

    err = _ensure_ov2_clone()
    if err:
        return err

    target = OV2_CLONE_DIR / ov2_page_path
    if not target.exists():
        return f"Target OV2 page not found in current OV2 clone: {ov2_page_path}"

    content = _read(target)
    section_header = "## Related Claude Threads"
    entry = f"- {pointer_line}"
    if section_header in content:
        content = content.rstrip() + f"\n{entry}\n"
    else:
        content = content.rstrip() + f"\n\n{section_header}\n{entry}\n"
    target.write_text(content, encoding="utf-8")

    _ov2_git(["config", "user.email", "claude-ov-xref@eoxs.com"])
    _ov2_git(["config", "user.name", "Threads OV Cross-Reference"])
    _ov2_git(["add", ov2_page_path])
    commit = _ov2_git(["commit", "-m", f"xref: link Threads OV chat summary to {Path(ov2_page_path).stem}"])
    if commit.returncode != 0 and "nothing to commit" not in (commit.stdout + commit.stderr):
        return f"git commit into OV2 failed: {commit.stderr.strip()}"
    push = _ov2_git(["push", "origin", f"HEAD:{OV2_BRANCH}"])
    if push.returncode != 0:
        return f"git commit succeeded locally but push to OV2 failed: {push.stderr.strip()}"

    staged_file.unlink()
    return f"Applied and pushed to OV2 ({OV2_BRANCH}): {ov2_page_path}\nAdded: {entry}"


# ── Entry Point ───────────────────────────────────────────────────────────────

def _init_postgres() -> bool:
    """Initialize PostgreSQL: create tables, sync users. Returns True if PG is available."""
    global _pg_available, _user_id_cache
    try:
        from db.connection import is_pg_available, create_tables
        if not is_pg_available():
            print("[db] DATABASE_URL not set or unreachable — running in Git-only fallback mode.")
            return False

        create_tables()

        # Sync all configured users into PG
        from db.queries import sync_users
        usernames = list(CLAUDE_OV_USERS.values())
        _user_id_cache = sync_users(usernames)
        print(f"[db] Synced {len(_user_id_cache)} users to PostgreSQL: {list(_user_id_cache.keys())}")
        return True

    except Exception as e:
        print(f"[db] PostgreSQL initialization failed — running in Git-only fallback mode: {e}\n"
              f"{traceback.format_exc()}", file=sys.stderr)
        return False


def _start_outbox_worker() -> None:
    """Start the outbox worker as a background thread."""
    try:
        from worker import start_worker_thread
        start_worker_thread()
        print("[worker] Outbox worker started as background thread.")
    except ImportError:
        print("[worker] worker.py not found — outbox worker not started. "
              "Markdown/Git projection will not run until worker.py is created.")
    except Exception as e:
        print(f"[worker] Failed to start outbox worker: {e}", file=sys.stderr)


if __name__ == "__main__":
    print(f"Starting Thread-Vault MCP Server v2 on port {PORT}")
    print(f"Vault root: {VAULT_ROOT.resolve()}")

    # Initialize PostgreSQL (graceful degradation if unavailable)
    _pg_available = _init_postgres()
    print(f"PostgreSQL: {'ENABLED ✓' if _pg_available else 'DISABLED — Git-only fallback'}")

    # Start outbox worker if PG is available
    if _pg_available:
        _start_outbox_worker()

    print(f"Saved chat transcripts (filesystem): {len(_all_md(CHAT_DIR))}")
    print(f"Chat summaries: {len(_all_md(CHAT_SUMMARIES_DIR))}")
    print(f"Saved analyses (filesystem): {len(_all_md(ANALYSES_DIR))}")
    staged_count = len(list(OV2_XREF_STAGING.glob('*.md'))) if OV2_XREF_STAGING.exists() else 0
    print(f"Staged OV2 cross-references awaiting approval: {staged_count}")
    print(f"Write access to own repo (GITHUB_TOKEN): {'enabled' if GITHUB_TOKEN else 'DISABLED — saves will stay local only, not push'}")
    print(f"Write access to OV2 repo (OV2_GITHUB_TOKEN): {'enabled' if OV2_GITHUB_TOKEN else 'DISABLED — propose_ov2_xref/apply_ov2_xref will not be able to reach OV2'}")
    print(f"Git branch: {GIT_BRANCH}")
    print(f"Configured users: {len(CLAUDE_OV_USERS)} (secrets not logged)")
    print(f"Per-user endpoints mounted at /<their-secret>/sse (each resolves to one username)")
    if _pg_available:
        print(f"Threads API: POST /<secret>/api/v1/threads/events, POST /<secret>/api/v1/threads/checkpoint")

    # mcp.run(transport="sse") builds and serves its own uvicorn app internally
    # with no hook to inject middleware — so the identity-resolving middleware
    # is wired in manually here instead: get the raw ASGI app, wrap it, run it.
    import uvicorn
    from starlette.middleware.cors import CORSMiddleware

    app = _IdentityMiddleware(mcp.sse_app())
    cors_app = CORSMiddleware(
        app,
        allow_origins=["*"],
        allow_methods=["*"],
        allow_headers=["*"],
    )
    uvicorn.run(cors_app, host="0.0.0.0", port=PORT)
